### ISSUE TITLE
Import AoModAI's pre-VCS history

### ISSUE THREAD

**Issue by Deltik** [Retherichus/AoModAI#1]
Hi there!

I downloaded all of your past AoModAI releases [from your OneDrive](https://onedrive.live.com/?authkey=%21APnFpVMtV40AxTI&id=65304DD80F44E7A2%211696&cid=65304DD80F44E7A2) and painstakingly massaged the releases to be Git-compatible.  This way, you can view diffs between releases to see what changed.

In addition to revision history, I've also tagged all your past releases marked as "stable" or "release" in their folder name.

The generated commit history is here: https://github.com/Deltik/AoModAI/commits/Test-builds
The generated tags are here: https://github.com/Deltik/AoModAI/tags

You can import both the commits and the tags with the caveat that your entire repository's history will be overwritten (which shouldn't be much impact at this early stage of your repository).

**Important:** Do not commit anything more to your `Test-builds` branch after [Hmm. what? (`ac3e79e`)](https://github.com/Retherichus/AoModAI/commit/ac3e79ef27f48fb899fa074475d27fa58b88bf2d).

To import this revised history into your `Test-builds` branch, run these commands:

1. `git remote add downstream https://github.com/Deltik/AoModAI.git`
   This adds my fork as a remote to your Git working directory.
2. `git fetch downstream`
   At this point, you'll see the new branch `downstream/Test-builds` and the 17 tags.
3. `git branch -m Test-builds Test-builds-old`
   This will rename your current `Test-builds` to `Test-builds-old` to make room for the revised `Test-builds` branch.
4. `git checkout -b Test-builds downstream/Test-builds`
   This sets up the revised `Test-builds` branch on your local machine.
5. `git push --force origin Test-builds`
   This overwrites your GitHub `Test-builds` branch with the revised one.
5. `git push --tags origin`
   This imports the tags of your past releases and stable versions into GitHub, which you can browse at https://github.com/Retherichus/AoModAI/tags

The `master` branch can also be rewritten with these commands:

1. `git branch -m master master-old`
2. `git checkout -b master 2f68b68029c2d81e6f2ef43c7bde5292c4adee39`
3. `git push --force origin master`

Cleanup commands:

1. `git remote remove downstream`
   Remove my forked repository from your local machine
2. `git branch -D Test-builds-old`
   Remove the old `Test-builds` branch
3. `git branch -D master`
   Remove the old `master` branch

**Comment by Deltik** [comment]
FYI, here's the hacky shell script that I wrote to import the old OneDrive releases into the Git repo:

```bash
#!/bin/bash

CWD=$(pwd)

SORTED=$(ls "AoModAI EE/" | while read line
do
        cd "AoModAI EE/$line"
        newestfile=$(ls -Art --group-directories-first | tail -n 1)
        DATE_EPOCH=$(stat -c '%Y' "$newestfile")
        echo "$DATE_EPOCH - $line"
        cd "$CWD"
done | sort -h)

echo "$SORTED" | while read line
do
        DATE_EPOCH=$(echo "$line" | awk -F' - ' '{print $1}')
        DIRNAME=$(echo "$line" | awk -F' - ' '{print $2}')
        GIT_DATE=$(date -u -d "@$DATE_EPOCH")
        DATE=$(date -u -d "@$DATE_EPOCH" "+%Y-%m-%d")
        NEXT_MAJOR=$(date -u -d "@$DATE_EPOCH" "+%Y.%m.%d")
        if [[ "$NEXT_MAJOR" == "$LAST_MAJOR" ]]
        then
                MINOR=$((MINOR+1))
        else
                LAST_MAJOR="$NEXT_MAJOR"
                MINOR=""
        fi

        if [[ -z "$MINOR" ]]
        then
                GIT_TAG="v$LAST_MAJOR"
        else
                GIT_TAG="v$LAST_MAJOR.$MINOR"
        fi

        if echo "$DIRNAME" | grep -vi 'unstable' | grep -qiP '(rel|stab)'
        then
                RELEASE=" (RELEASE)"
        else
                unset RELEASE
        fi

        echo "$DATE_EPOCH - $GIT_DATE - $GIT_TAG$RELEASE - ${DIRNAME}"

        rsync --delete -avHXShPs --exclude=".git" "AoModAI EE/$DIRNAME/" "AoModAI/"
        cd "AoModAI/"
        git add -A
        if [[ -n "$RELEASE" ]]
        then
                git tag -s -a "$GIT_TAG" -m "Stable release last modified $DATE" -m "$DIRNAME"
        fi
        GIT_AUTHOR_DATE="$GIT_DATE" GIT_COMMITTER_DATE="$GIT_DATE" git commit --author="Retherichus <32375067+Retherichus@users.noreply.github.com>" -S -m "$DIRNAME"
        cd "$CWD"
done
```

Before running the script, I put the old releases in a folder called `AoModAI EE` and ensured each release folder looked the same for the most part.

After running the script, I used some Git rebasing and filter-branch trickery to write the history as if AoModAI had been on Git all along.

**Comment by Retherichus** [comment]
Hey! Oh wow, I'm speechless.. I really don't know what to say.. 
This sounds like a very complex, and not to say.. a very time consuming task to go through! 
But! this is simply just amazing! I just can't thank you enough for doing this! :D

Okay, so let's give this a shot!
As detailed as the guide is, I'm sure I'm going to screw up on something.. 
I kinda failed at the don't make a new commit part as I saw your post a little bit too late.. but I have a backup handy on my local drive, so it should be okay even if it gets wiped!
Here goes.. :O

**Comment by Deltik** [comment]
@Retherichus: I accounted for your latest commit (ac3e79ef27f48fb899fa074475d27fa58b88bf2d) already and have added it to the new history chain as 3681df2b7cfaac6be9617494e7ed0f3532433106.

**Comment by Retherichus** [comment]
Oh, haha, I was wondering why it didn't show up the changes I did earlier this day. :D
Though, I ran into some permission issues when I tried to update it just now, but it came through as soon as I restarted the github desktop program. :)

So, um..  I can see that there's tons of new and old  commits when viewing the project, I suppose this means everything is successful? :D
If I screwed up, let me know and I'll try to fix it... even though I'm totally clueless. hah.
Again - thank you so much!

**Comment by Retherichus** [comment]
Oops, re-opened. :o

**Comment by Deltik** [comment]
Awesome!  I'm glad I was able to help.  The revised history and tags do appear to have been applied successfully.

Here are some optional action items I suggest:

- Add a license for AoModAI.  This allows the open source community to build on your work.  [Choose a license](https://choosealicense.com/) and [add it to your repository](https://help.github.com/articles/adding-a-license-to-a-repository/).
- You can now [add release notes](https://github.com/Retherichus/AoModAI/tags) to each tag with a summary documenting milestones in each AoModAI release.
- Consider [adding a readme](https://help.github.com/articles/about-readmes/) to help people who land on your GitHub repo understand AoModAI.  If you make a `README.md` file, you can make it look nice with Markdown.  [StackEdit.io](https://stackedit.io/editor) is a good online Markdown editor.
- If you have some extra time, here is [a good article on best practices for Git commit messages](https://chris.beams.io/posts/git-commit/).
